### ISSUE TITLE
Getting `java.util.ConcurrentModificationException` when running `bloopInstall`, Scala 2.12

### ISSUE THREAD

**Issue by Guidoooch** [scalacenter/gradle-bloop#41]
### Describe the bug

Hello, when executing bloopInstall in a big mono-repo project, mainly Scala, the command fails with the following:

```zsh
➜  project git:(main) ✗ ./gradlew bloopInstall

Task :module:sub-module:bloopInstall FAILED
FAILURE: Build failed with an exception.

What went wrong: 
Execution failed for task ':module:sub-module:bloopInstall'.
java.util.ConcurrentModificationException (no error message)
```

I can confirm that with gradle-bloop 1.5.6 this doesn't happen.

### Expected behavior

The `bloopInstall` command exports the gradle build correctly.

### Operating system

Linux

### Version of Gradle

7.5.1

### Version of gradle-bloop

1.5.8, 1.6.0

### Version of Bloop

1.5.6

**Comment by Guidoooch** [comment]
One more information, I believe this error is related to bloop 1.5.6, as it seems to be working with bloop 1.5.5

**Comment by Guidoooch** [comment]
Thank you, the import will be so slow, for now I'll use 1.5.6 and forget about vs code

**Comment by ckipp01** [comment]
> Likely the same as https://github.com/scalacenter/gradle-bloop/issues/32 and should be fixed. I don't think there's been a release since.

I can go ahead and cut a release. It's been quite some time.
